
// Mock continue watching data
export const continueWatchingItems = [
  {
    id: "1",
    title: "The Batman",
    imageUrl: "/placeholder.svg?height=450&width=800",
    progress: 75,
    type: "movie" as const,
    watchUrl: "/watch/1",
  },
  {
    id: "3",
    title: "Stranger Things",
    imageUrl: "/placeholder.svg?height=450&width=800",
    progress: 60,
    type: "series" as const,
    episodeInfo: "S4:E5",
    watchUrl: "/series/3/watch/4/5",
  },
  {
    id: "6",
    title: "Oppenheimer",
    imageUrl: "/placeholder.svg?height=450&width=800",
    progress: 30,
    type: "movie" as const,
    watchUrl: "/watch/6",
  },
  {
    id: "2",
    title: "Breaking Bad",
    imageUrl: "/placeholder.svg?height=450&width=800",
    progress: 90,
    type: "series" as const,
    episodeInfo: "S3:E7",
    watchUrl: "/series/2/watch/3/7",
  },
  {
    id: "8",
    title: "Poor Things",
    imageUrl: "/placeholder.svg?height=450&width=800",
    progress: 50,
    type: "movie" as const,
    watchUrl: "/watch/8",
  },
  {
    id: "83",
    title: "Poor Things",
    imageUrl: "/placeholder.svg?height=450&width=800",
    progress: 50,
    type: "movie" as const,
    watchUrl: "/watch/8",
  },
  {
    id: "82",
    title: "Poor Things",
    imageUrl: "/placeholder.svg?height=450&width=800",
    progress: 50,
    type: "movie" as const,
    watchUrl: "/watch/8",
  },
  {
    id: "81",
    title: "Poor Things",
    imageUrl: "/placeholder.svg?height=450&width=800",
    progress: 50,
    type: "movie" as const,
    watchUrl: "/watch/8",
  },
  {
    id: "80",
    title: "Poor Things",
    imageUrl: "/placeholder.svg?height=450&width=800",
    progress: 50,
    type: "movie" as const,
    watchUrl: "/watch/8",
  },
]
//trending movies
export const trendingMovies = [

  {
    id: "1",
    title: "The Batman",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.5
  },
  {
    id: "2",
    title: "Top Gun: Maverick",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.7,
  },
  {
    id: "3",
    title: "Everything Everywhere All at Once",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.9,
  },
  {
    id: "4",
    title: "The Whale",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.3,
  },
  {
    id: "55",
    title: "Black Panther: Wakanda Forever",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.4,
  },
  {
    id: "54",
    title: "Black Panther: Wakanda Forever",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.4,
  },
  {
    id: "53",
    title: "Black Panther: Wakanda Forever",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.4,
  },
  {
    id: "52",
    title: "Black Panther: Wakanda Forever",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.4,
  },
  {
    id: "51",
    title: "Black Panther: Wakanda Forever",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.4,
  },
  {
    id: "50",
    title: "Black Panther: Wakanda Forever",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.4,
  },
]

export const popularSeries = [

  {
    id: "1",
    title: "Stranger Things",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.8,
    seasons: 4,
  },
  {
    id: "2",
    title: "Breaking Bad",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.9,
    seasons: 5,
  },
  {
    id: "3",
    title: "The Last of Us",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.7,
    seasons: 1,
  },
  {
    id: "4",
    title: "Game of Thrones",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.6,
    seasons: 8,
  },
  {
    id: "5",
    title: "The Mandalorian",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.5,
    seasons: 3,
  },
  {
    id: "44",
    title: "Game of Thrones",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.6,
    seasons: 8,
  },
  {
    id: "43",
    title: "Game of Thrones",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.6,
    seasons: 8,
  },
  {
    id: "42",
    title: "Game of Thrones",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.6,
    seasons: 8,
  },
  {
    id: "41",
    title: "Game of Thrones",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.6,
    seasons: 8,
  },
]

// Mock movie data
export const allMovies = [
  {
    id: "1",
    title: "The Batman",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.5,
    year: 2022,
    genre: "Action",
  },
  {
    id: "2",
    title: "Top Gun: Maverick",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.7,
    year: 2022,
    genre: "Action",
  },
  {
    id: "3",
    title: "Everything Everywhere All at Once",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.9,
    year: 2022,
    genre: "Sci-Fi",
  },
  {
    id: "4",
    title: "The Whale",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.3,
    year: 2022,
    genre: "Drama",
  },
  {
    id: "5",
    title: "Black Panther: Wakanda Forever",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.4,
    year: 2022,
    genre: "Action",
  },
  {
    id: "6",
    title: "Oppenheimer",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.8,
    year: 2023,
    genre: "Drama",
  },
  {
    id: "7",
    title: "Barbie",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.2,
    year: 2023,
    genre: "Comedy",
  },
  {
    id: "8",
    title: "Poor Things",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.6,
    year: 2023,
    genre: "Drama",
  },
  {
    id: "9",
    title: "Killers of the Flower Moon",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.5,
    year: 2023,
    genre: "Crime",
  },
  {
    id: "10",
    title: "The Zone of Interest",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.7,
    year: 2023,
    genre: "Drama",
  },
  {
    id: "11",
    title: "Dune",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.6,
    year: 2021,
    genre: "Sci-Fi",
  },
  {
    id: "12",
    title: "The French Dispatch",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.1,
    year: 2021,
    genre: "Comedy",
  },
  {
    id: "13",
    title: "No Time to Die",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.0,
    year: 2021,
    genre: "Action",
  },
  {
    id: "14",
    title: "The Power of the Dog",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.4,
    year: 2021,
    genre: "Drama",
  },
  {
    id: "15",
    title: "Spider-Man: No Way Home",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.5,
    year: 2021,
    genre: "Action",
  },
  {
    id: "16",
    title: "Dune: Part Two",
    imageUrl: "/placeholder.svg?height=450&width=300",
    rating: 4.8,
    year: 2024,
    genre: "Sci-Fi",
  },
]
